name: Package Project
on: [ workflow_dispatch, workflow_call ]
jobs:
  get_version:
    uses: ./.github/workflows/get-version.yml

  package_jar:
    name: "Create Linux Artifacts"
    needs: [ get_version ]
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v4
      - name: "Setup Java Dependencies"
        run: |
          sudo apt update
          sudo apt install openjdk-21-jdk-headless maven
      - name: "Maven Package"
        run: mvn package
      - name: "Upload Artifacts"
        uses: actions/upload-artifact@v4
        with:
          name: artifacts
          path: |
            ./target/*.jar
            ./src/main/resources/*.toml