name: Create Release Draft
on: workflow_dispatch
jobs:
  get_version:
    uses: ./.github/workflows/get-version.yml

  package:
    uses: ./.github/workflows/package.yml

  create_release_draft:
    needs: [ get_version, package ]
    runs-on: ubuntu-latest
    steps:
      - name: "Download Artifacts"
        uses: actions/download-artifact@v4
      - name: "Create Release"
        uses: softprops/action-gh-release@v2
        with:
          name: "Release ${{ needs.get_version.outputs.version }}"
          tag_name: "v${{ needs.get_version.outputs.version }}"
          body: "TODO: Write Changelog"
          draft: true
          prerelease: true
          fail_on_unmatched_files: true
          files: |
            ./artifacts/*.jar