name: "Verify Project"
on: [ push, pull_request, workflow_call ]
jobs:
  verify_linux:
    name: "Verify Build for Linux"
    runs-on: ubuntu-22.04
    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v4
      - name: "Setup Java"
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '21'
          cache: 'maven'
      - name: "Maven Verify"
        run: mvn verify