name: "Verify Project"
on: [ push, pull_request, workflow_call ]
jobs:
  verify_linux:
    name: "Verify Build for Linux"
    runs-on: ubuntu-22.04
    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v4
      - name: "Setup Java Dependencies"
        run: |
          sudo apt update
          sudo apt install openjdk-21-jdk-headless maven
      - name: "Maven Verify"
        run: mvn verify